server:
  port: 8088

spring:
  application:
    name: files-transfer
  # Spring 文件上传配置
  servlet:
    multipart:
      enabled: true
      # 单文件上传 单文件大小最大限制
      max-file-size: 500MB
      # 一次请求的多个文件总大小限制
      max-request-size: 1GB


files:
  transfer:
    # 文件传输 服务器 地址前缀
    urlPrefix: D:\home
    # 文件传输 服务器 上传地址
    uploadUrl: ${files.transfer.urlPrefix}\temp
